name: Update Nonce and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Generate HTML and JS with hash
      run: node sc.js

    - name: Add generated files to Git
      run: |
        git add .
        git commit -m "Update generated files with hashed names"

    - name: Git configuration
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions@github.com"

    - name: Stash unstaged changes (if any)
      run: |
        git diff --quiet || git stash save "Unstaged changes"

    - name: Pull remote changes and push updates
      run: |
        git pull origin main --rebase  # Pull the latest changes from the remote repository
        git push origin main  # Push your local changes to the remote repository

    - name: Pop stashed changes (if any)
      run: |
        if git stash list | grep -q "Unstaged changes"; then git stash pop; fi
